#!/usr/bin/env python3
"""Project tasks/events.jsonl into tasks/metrics.md — what each team spent,
per task, per phase.

Generated view, never hand-edited (same rule as board.md/kanban.md — D9/D10).
Reads the `payload.metrics` object move_task.py optionally attaches to a
`task.phase_changed` event (team/tokens/cost_usd/duration_seconds/cycles —
recorded against the phase the move is LEAVING, since that's when the work
is actually finished). A move with no --team/--tokens/etc. simply has no
metrics and doesn't appear here.

This exists to build a real, queryable history of team performance per
phase — see tasks/README.md's "Orchestration architecture" section, "these
metrics will later be used to improve orchestration or build team
profiles." Nothing here does that analysis yet; this is only the
projection the analysis would read.
"""
import json
from pathlib import Path

TASKS_DIR = Path(__file__).parent
EVENTS_FILE = TASKS_DIR / "events.jsonl"
VIEW_FILE = TASKS_DIR / "metrics.md"

PHASE_CHANGED_TYPES = ("task.phase_changed",)


def load_events():
    if not EVENTS_FILE.exists():
        return []
    events = []
    for line in EVENTS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            events.append(json.loads(line))
    events.sort(key=lambda e: e["ts"])
    return events


def project(events):
    """Returns a flat list of {task_id, phase, team, tokens, cost_usd,
    duration_seconds, cycles, ts} rows, one per phase-transition that
    carried metrics — i.e. per phase actually worked, not per task."""
    rows = []
    for ev in events:
        if ev["type"] not in PHASE_CHANGED_TYPES:
            continue
        payload = ev.get("payload") or {}
        metrics = payload.get("metrics")
        if not metrics:
            continue
        rows.append({
            "task_id": ev.get("task_id"),
            "phase": payload.get("from_phase"),  # the phase the metrics were spent IN
            "team": metrics.get("team", ""),
            "tokens": metrics.get("tokens"),
            "cost_usd": metrics.get("cost_usd"),
            "duration_seconds": metrics.get("duration_seconds"),
            "cycles": metrics.get("cycles"),
            "ts": ev["ts"],
        })
    return rows


def fmt(v, suffix=""):
    return "" if v is None else f"{v}{suffix}"


def render(rows):
    lines = [
        "# metrics.md",
        "",
        "**Generated by `rebuild_metrics.py` from `events.jsonl` — do not hand-edit.**",
        "Metrics come from `move_task.py`'s optional --team/--tokens/--cost-usd/",
        "--duration-seconds/--cycles flags, recorded against the phase being left.",
        "",
        "## Per phase-transition",
        "",
        "| task_id | phase | team | tokens | cost_usd | duration_s | cycles | ts |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['task_id']} | {r['phase']} | {r['team']} | {fmt(r['tokens'])} | "
            f"{fmt(r['cost_usd'])} | {fmt(r['duration_seconds'])} | {fmt(r['cycles'])} | {r['ts']} |"
        )

    lines += ["", "## Totals by team", "", "| team | phases | tokens | cost_usd | duration_s | cycles |", "|---|---|---|---|---|---|"]
    by_team = {}
    for r in rows:
        agg = by_team.setdefault(r["team"] or "(sem equipa)", {"phases": 0, "tokens": 0, "cost_usd": 0.0, "duration_seconds": 0, "cycles": 0})
        agg["phases"] += 1
        agg["tokens"] += r["tokens"] or 0
        agg["cost_usd"] += r["cost_usd"] or 0.0
        agg["duration_seconds"] += r["duration_seconds"] or 0
        agg["cycles"] += r["cycles"] or 0
    for team in sorted(by_team):
        a = by_team[team]
        lines.append(f"| {team} | {a['phases']} | {a['tokens']} | {round(a['cost_usd'], 4)} | {a['duration_seconds']} | {a['cycles']} |")

    lines += ["", "## Totals by task", "", "| task_id | phases | tokens | cost_usd | duration_s | cycles |", "|---|---|---|---|---|---|"]
    by_task = {}
    for r in rows:
        agg = by_task.setdefault(r["task_id"], {"phases": 0, "tokens": 0, "cost_usd": 0.0, "duration_seconds": 0, "cycles": 0})
        agg["phases"] += 1
        agg["tokens"] += r["tokens"] or 0
        agg["cost_usd"] += r["cost_usd"] or 0.0
        agg["duration_seconds"] += r["duration_seconds"] or 0
        agg["cycles"] += r["cycles"] or 0
    for task_id in sorted(by_task):
        a = by_task[task_id]
        lines.append(f"| {task_id} | {a['phases']} | {a['tokens']} | {round(a['cost_usd'], 4)} | {a['duration_seconds']} | {a['cycles']} |")

    lines.append("")
    return "\n".join(lines)


def main():
    events = load_events()
    rows = project(events)
    VIEW_FILE.write_text(render(rows), encoding="utf-8")
    print(f"wrote {VIEW_FILE} ({len(rows)} metered phase-transitions from {len(events)} events)")


if __name__ == "__main__":
    main()
