#!/bin/bash
# Codex CLI: current wire_api only supports "responses" (/v1/responses) -- "chat" was
# removed and raises an error on load (verified in codex-rs/model-provider-info/src/lib.rs,
# CHAT_WIRE_API_REMOVED_ERROR). A plain openai-compat chat/completions server therefore
# can't be registered directly; this adapter points Codex at the shared local LiteLLM
# proxy instead, which bridges /v1/responses -> /v1/chat/completions.
#
# Registers a [profiles.<id>] entry rather than overwriting the global default
# model_provider/model, so existing Codex usage is unaffected until the user opts in
# with `codex --profile <id>`.

set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
source lib.sh

action="${1:-}"
provider_id="${2:-}"
[[ -n $action && -n $provider_id ]] || dtx_fail "usage: codex.sh <apply|remove> <provider-id>"
command -v jq >/dev/null || dtx_fail "jq is required"

provider=$(dtx_provider_json "$provider_id")
harness=$(dtx_harness_json codex)
config_path=$(dtx_expand_path "$(jq -r .configPath <<<"$harness")")

begin_mark="# BEGIN dtx-providers: $provider_id"
end_mark="# END dtx-providers: $provider_id"

strip_block() {
  # See crush.sh's strip_block for why this is prefix-then-boundary, not ==
  # or a bare prefix match.
  awk -v b="$begin_mark" -v e="$end_mark" '
    function starts_with_marker(line, mark,    blen, rest) {
      blen = length(mark)
      if (substr(line, 1, blen) != mark) return 0
      rest = substr(line, blen + 1, 1)
      return (rest == "" || rest == " " || rest == "\t")
    }
    starts_with_marker($0, b) { skip = 1; begins++; next }
    starts_with_marker($0, e) { skip = 0; ends++; next }
    !skip { print }
    END { if (begins != ends) { print "dtx-providers: unpaired BEGIN/END marker in '"$config_path"', refusing to touch it" > "/dev/stderr"; exit 1 } }
  ' "$config_path"
}

case "$action" in
apply)
  ../proxy/ensure-proxy.sh

  mkdir -p "$(dirname "$config_path")"
  touch "$config_path"
  dtx_backup "$config_path"

  display_name=$(jq -r .displayName <<<"$provider")
  model_id=$(jq -r '.models[0].id' <<<"$provider")

  block=$(cat <<EOF
$begin_mark  (managed by dtx-providers-tui, do not edit by hand)
[model_providers.$provider_id]
name = "$display_name (via local proxy)"
base_url = "http://127.0.0.1:4444"
env_key = "DTX_PROXY_MASTER_KEY"
wire_api = "responses"

[profiles.$provider_id]
model_provider = "$provider_id"
model = "$model_id"
$end_mark
EOF
  )

  tmp=$(mktemp)
  strip_block >"$tmp"
  { cat "$tmp"; echo; echo "$block"; } >"$config_path"
  rm -f "$tmp"

  launcher="$HOME/.local/bin/codex-$provider_id"
  mkdir -p "$(dirname "$launcher")"
  cat >"$launcher" <<EOF
#!/bin/bash
# Generated by dtx-providers-tui -- do not edit by hand. Regenerate via:
#   dtx-providers-tui apply codex $provider_id
set -a
source "\$HOME/.dtx-providers/proxy.env"
set +a
exec codex --profile $provider_id "\$@"
EOF
  chmod +x "$launcher"

  echo "codex: applied $provider_id -> $config_path"
  echo "codex: run 'codex-$provider_id' instead of 'codex --profile $provider_id' (sets DTX_PROXY_MASTER_KEY for you)"
  ;;
remove)
  [[ -f $config_path ]] || { echo "codex: no config at $config_path, nothing to remove"; exit 0; }
  tmp=$(mktemp)
  strip_block >"$tmp"
  mv "$tmp" "$config_path"
  rm -f "$HOME/.local/bin/codex-$provider_id"
  echo "codex: removed $provider_id -> $config_path"
  ;;
*)
  dtx_fail "unknown action: $action"
  ;;
esac
