#!/bin/bash
# Gemini CLI: `GOOGLE_GEMINI_BASE_URL` overrides the base URL "when using
# gemini-api-key authentication" and explicitly allows plain http:// for
# localhost (docs/reference/configuration.md in google-gemini/gemini-cli,
# verified 2026-09-17 -- the docs/cli/settings.md and docs/cli/model.md pages
# checked earlier do NOT cover this env var, which is why an earlier version
# of this adapter wrongly said "unsupported"). LiteLLM's proxy exposes the
# actual Gemini wire format at POST /v1beta/models/{model}:generateContent
# (litellm/proxy/google_endpoints/endpoints.py), routed through the same
# model_list as every other provider here -- same proxy, same
# ensure-proxy.sh, same pattern as codex.sh/claude-code.sh.
#
# NOT YET SMOKE-TESTED end-to-end (the google_endpoints bridge is recent
# LiteLLM code) -- confirm with a real `gemini-<id> "hello"` once
# litellm[proxy] is installed before trusting this in daily use.

set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
source lib.sh

action="${1:-}"
provider_id="${2:-}"
[[ -n $action && -n $provider_id ]] || dtx_fail "usage: gemini-cli.sh <apply|remove> <provider-id>"
command -v jq >/dev/null || dtx_fail "jq is required"

provider=$(dtx_provider_json "$provider_id")
launcher="$HOME/.local/bin/gemini-$provider_id"

case "$action" in
apply)
  ../proxy/ensure-proxy.sh

  model_id=$(jq -r '.models[0].id' <<<"$provider")
  model_name="$provider_id/$model_id"

  mkdir -p "$(dirname "$launcher")"
  cat >"$launcher" <<EOF
#!/bin/bash
# Generated by dtx-providers-tui -- do not edit by hand. Regenerate via:
#   dtx-providers-tui apply gemini-cli $provider_id
set -a
source "\$HOME/.custom_providers/proxy.env"
set +a
export GOOGLE_GEMINI_BASE_URL="http://127.0.0.1:4444"
export GEMINI_API_KEY="\$DTX_PROXY_MASTER_KEY"
exec gemini --model "$model_name" "\$@"
EOF
  chmod +x "$launcher"
  echo "gemini-cli: wrote $launcher (run 'gemini-$provider_id' instead of 'gemini' to use $provider_id)"
  ;;
remove)
  rm -f "$launcher"
  echo "gemini-cli: removed $launcher"
  ;;
*)
  dtx_fail "unknown action: $action"
  ;;
esac
