#!/usr/bin/env python3
"""Project tasks/events.jsonl into tasks/board.md — a generated view, never hand-edited.

D9/D10 (Workspace Agil doc): the JSONL log is the source of truth; every
other representation (this table, a future SQLite index) is a disposable,
rebuildable projection. Re-run this script any time events.jsonl changes.

Column names are English (workspace default since 2026-09-16, see
language.userFacing in workspace-standards.yaml). Events written before
log is append-only, so those historical lines are never rewritten; this
script reads either spelling (PT falls back when the EN key is absent).
"""
import json
from pathlib import Path

TASKS_DIR = Path(__file__).parent
EVENTS_FILE = TASKS_DIR / "events.jsonl"
VIEW_FILE = TASKS_DIR / "board.md"

COLUMNS = [
    "id", "title", "project", "status", "energy",
    "estimate", "deadline", "blocked_by", "origin", "created", "touched",
]

# English key -> legacy Portuguese key, for reading events written before
# the 2026-09-16 language-default change. New events should use the
# English keys only; this map exists purely to project old log lines.
LEGACY_PT_KEYS = {
    "title": "titulo",
    "project": "projeto",
    "status": "estado",
    "energy": "energia",
    "estimate": "estimativa",
    "deadline": "prazo",
    "blocked_by": "bloqueado_por",
    "origin": "origem",
}


def payload_get(payload, key, default=""):
    if key in payload:
        return payload[key]
    legacy_key = LEGACY_PT_KEYS.get(key)
    if legacy_key and legacy_key in payload:
        return payload[legacy_key]
    return default


def event_get(ev, key, default=""):
    if key in ev:
        return ev[key]
    legacy_key = LEGACY_PT_KEYS.get(key)
    if legacy_key and legacy_key in ev:
        return ev[legacy_key]
    return default


def load_events():
    if not EVENTS_FILE.exists():
        return []
    events = []
    for line in EVENTS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            events.append(json.loads(line))
    events.sort(key=lambda e: e["ts"])
    return events


CREATED_TYPES = ("tarefa.criada", "task.created")
STATUS_CHANGED_TYPES = ("tarefa.estado_mudou", "task.status_changed")


def project(events):
    """Last event wins per task_id (D10). Returns dict[task_id] -> row."""
    tasks = {}
    for ev in events:
        task_id = ev.get("task_id")
        if not task_id:
            continue  # events not tied to a task (e.g. session-level) don't appear in the table
        payload = ev.get("payload") or {}
        row = tasks.setdefault(task_id, {col: "" for col in COLUMNS})
        row["id"] = task_id

        if ev["type"] in CREATED_TYPES:
            row["title"] = payload_get(payload, "title", row["title"])
            row["project"] = payload_get(payload, "project", row["project"])
            row["energy"] = payload_get(payload, "energy", row["energy"])
            row["estimate"] = payload_get(payload, "estimate", row["estimate"])
            row["deadline"] = payload_get(payload, "deadline", row["deadline"])
            row["blocked_by"] = payload_get(payload, "blocked_by", row["blocked_by"])
            row["origin"] = payload_get(payload, "origin", row["origin"])
            row["status"] = event_get(ev, "status", row["status"])
            row["created"] = ev["ts"]
        elif ev["type"] in STATUS_CHANGED_TYPES:
            row["status"] = payload_get(payload, "status", row["status"])
            blocked_by = payload_get(payload, "blocked_by", None)
            if blocked_by is not None:
                row["blocked_by"] = blocked_by or ""
        row["touched"] = ev["ts"]

    return tasks


def render(tasks):
    lines = [
        "# board.md",
        "",
        "**Generated by `rebuild_view.py` from `events.jsonl` — do not hand-edit.**",
        "To change a task, append an event with `append_event.py` and re-run this script.",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "|".join(["---"] * len(COLUMNS)) + "|",
    ]
    for task_id in sorted(tasks, key=lambda tid: tasks[tid]["created"]):
        row = tasks[task_id]
        lines.append("| " + " | ".join(str(row[col]) for col in COLUMNS) + " |")
    lines.append("")
    return "\n".join(lines)


def main():
    events = load_events()
    tasks = project(events)
    VIEW_FILE.write_text(render(tasks), encoding="utf-8")
    print(f"wrote {VIEW_FILE} ({len(tasks)} tasks from {len(events)} events)")


if __name__ == "__main__":
    main()
